### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by kokinarido** [jonhoo/fantoccini#1]
Or under development?

**Comment by jonhoo** [comment]
That depends on your requirements for "production ready". It has not been used in production anywhere as far as I know, though I've been using it myself for a couple of smaller projects. I don't think there are any major instabilities or known defects at the moment, though deploying it in a larger environment is the only way to find out.

**Comment by kokinarido** [comment]
Ok. Is there a way to run on a server, that is, without a physical display?

**Comment by jonhoo** [comment]
What you're looking for is a browser than can run in "headless" mode. [phantomjs](http://phantomjs.org/) is a relatively common tool for that. [Google Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) also now has support for `--headless` , and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1338004) is getting it too in not too long. They both need you to run a "driver" for automation though. Chrome's is called `chromedrive`, and Firefox's is called `geckodriver`. I've had some issues getting the Chrome `--headless` flag to run correctly though, so another workaround (on Linux) is to use `xvfb-run`. That will spawn the browser window on a fake X screen, which causes nothing to appear.

**Comment by kokinarido** [comment]
yeah, but what about a rust library for `xvfb-run`? or can that a shell script, for example? for python I had to use a library in python for xvfb

**Comment by jonhoo** [comment]
I'm not sure what you're asking? `xvfb-run` is a command-line tool. So you would run, say:
```console
$ xvfb-run chromedriver --port=4444
```
That could also go in a shell script (just use `&` to make it run in the background). You can also launch it from Rust by using [`std::process::Command`](https://doc.rust-lang.org/std/process/struct.Command.html).

**Comment by kokinarido** [comment]
thanks
