### ISSUE TITLE
Add a way to handle alert window

### ISSUE THREAD

**Issue by POMMI3R** [jonhoo/fantoccini#103]
As I know, fantoccini doesn't have any way to handle alert window.

But it is one of the most important function in crawling.

Do you have any plan to add that function?

**Comment by jonhoo** [comment]
Hi! That is correct — I never got around to implementing support for [user prompts](https://html.spec.whatwg.org/#user-prompts). The WebDriver spec has some [specific methods in place](https://www.w3.org/TR/webdriver1/#user-prompts) that let you interact with them, so it shouldn't be _too_ hard to put something together. Unfortunately I'm very short on time these days, but if you want to give writing a PR a try, I'll try to find some time to review!

**Comment by POMMI3R** [comment]
Thanks.
