### ISSUE TITLE
Proxy with authentication is not supported

### ISSUE THREAD

**Issue by ghost** [jonhoo/fantoccini#112]
Hello,

Is there a way to use proxy with authorization.
The following code is used for `Client` configuration

```rust
let mut caps = serde_json::map::Map::new();
let opts = serde_json::json!({ "args": ["--headless"] });
caps.insert("moz:firefoxOptions".to_string(), opts.clone());
caps.insert(
    "proxy".to_string(),
    serde_json::json!({
        "proxyType": "manual",
        "httpProxy": proxy,
        "sslProxy": proxy,
    }),
);

let mut client = fantoccini::Client::with_capabilities("http://0.0.0.0:4444", caps).await?;
```

I tried to pass proxy value in two ways:
* When `proxy = "username:password@45.159.84.222:53002"` I get the following error:
**```unexpected webdriver error; webdriver returned error: httpProxy is not of the form host[:port]: username:password@45.159.84.222:53002```**

* When `proxy = "45.159.84.222:53002"` (without username and password):
**```WebDriverError { error: UnexpectedAlertOpen, message: \"Dismissed user prompt dialog: The proxy moz-proxy://45.159.84.222:53002 is requesting a username and password. The site says: “proxy”\", stack: \"\", delete_session: false }```**

* When `proxy = "45.159.84.222:53002"` and proxy config has the following format
```rust
{
    "proxyType": "manual",
    "httpProxy": proxy,
    "sslProxy": proxy,
    "socksUsername": "mi892oPJjV",
    "socksPassword": "EoxIdfl910",
}
```
this error is received
**```unexpected webdriver error; webdriver returned error: Invalid proxy configuration entry: socksPassword```**

Webdriver documentation says that it is possible to include credentials into url. ([link to docs](https://www.w3.org/TR/webdriver1/#proxy))

Also I've found the solution how to pass credentials to alert into `geckodriver` using Java lib, but I didn't find the way to do it from `fantoccini`. Maybe it would be useful for solution. ([link to comment](https://github.com/mozilla/geckodriver/issues/977#issuecomment-336230380))

**Comment by jonhoo** [comment]
Hmm, this _seems_ like it's a bug in `geckodriver` (or maybe in the `webdriver` crate), since we don't really do anything "special" with the credentials beyond passing them to the browser backend. Maybe it gets tripped up on capitalization in some way that the Java library deals with automatically? Does it work if you try to run it against `chromedriver` instead?

**Comment by jonhoo** [comment]
I'm going to close this under the assumption that this is a driver problem, and not a fantoccini bug.

**Comment by Niedzwiedzw** [comment]
> Hello,
> 
> Is there a way to use proxy with authorization. The following code is used for `Client` configuration
> 
> ```rust
> let mut caps = serde_json::map::Map::new();
> let opts = serde_json::json!({ "args": ["--headless"] });
> caps.insert("moz:firefoxOptions".to_string(), opts.clone());
> caps.insert(
>     "proxy".to_string(),
>     serde_json::json!({
>         "proxyType": "manual",
>         "httpProxy": proxy,
>         "sslProxy": proxy,
>     }),
> );
> 
> let mut client = fantoccini::Client::with_capabilities("http://0.0.0.0:4444", caps).await?;
> ```
> 
> I tried to pass proxy value in two ways:
> 
>     * When `proxy = "username:password@45.159.84.222:53002"` I get the following error:
>       **`unexpected webdriver error; webdriver returned error: httpProxy is not of the form host[:port]: username:password@45.159.84.222:53002`**
> 
>     * When `proxy = "45.159.84.222:53002"` (without username and password):
>       **`WebDriverError { error: UnexpectedAlertOpen, message: \"Dismissed user prompt dialog: The proxy moz-proxy://45.159.84.222:53002 is requesting a username and password. The site says: “proxy”\", stack: \"\", delete_session: false }`**
> 
>     * When `proxy = "45.159.84.222:53002"` and proxy config has the following format
> 
> 
> ```rust
> {
>     "proxyType": "manual",
>     "httpProxy": proxy,
>     "sslProxy": proxy,
>     "socksUsername": "mi892oPJjV",
>     "socksPassword": "EoxIdfl910",
> }
> ```
> 
> this error is received **`unexpected webdriver error; webdriver returned error: Invalid proxy configuration entry: socksPassword`**
> 
> Webdriver documentation says that it is possible to include credentials into url. ([link to docs](https://www.w3.org/TR/webdriver1/#proxy))
> 
> Also I've found the solution how to pass credentials to alert into `geckodriver` using Java lib, but I didn't find the way to do it from `fantoccini`. Maybe it would be useful for solution. ([link to comment](https://github.com/mozilla/geckodriver/issues/977#issuecomment-336230380))

hey, have you found a solution to this?

**Comment by maxcountryman** [comment]
This seems like an issue with `webdriver`, specifically [these checks](https://docs.rs/webdriver/latest/src/webdriver/capabilities.rs.html#345-346) are not to [spec](https://www.w3.org/TR/webdriver1/#proxy), which says: "The host may include credentials."
