### ISSUE TITLE
Bug: Some tests fail in non-English speaking countries.

### ISSUE THREAD

**Issue by xmeta** [jonhoo/fantoccini#113]
If you run the tests in a non-English speaking country, Some tests will fail.
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `"https://ja.wikipedia.org/wiki/Foobar"`,
 right: `"https://en.wikipedia.org/wiki/Foobar"`', tests\remote.rs:62:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `"https://ja.wikipedia.org/wiki/Foobar"`,
 right: `"https://en.wikipedia.org/wiki/Foobar"`', tests\remote.rs:46:5
test chrome::it_finds_sub_elements ... ok
thread '<unnamed>' panicked at 'test panicked: JoinError::Panic(...)', tests\remote.rs:269:9
test chrome::it_clicks ... FAILED
thread '<unnamed>' panicked at 'test panicked: JoinError::Panic(...)', tests\remote.rs:274:9
test chrome::it_clicks_by_locator ... FAILED
```
```
failures:
    chrome::it_clicks
    chrome::it_clicks_by_locator
    firefox::it_clicks
    firefox::it_clicks_by_locator
```
https://github.com/jonhoo/fantoccini/blob/b4cc6006d411fa531747ada5d1aabb95330dc3b9/tests/remote.rs#L35-L46
https://github.com/jonhoo/fantoccini/blob/b4cc6006d411fa531747ada5d1aabb95330dc3b9/tests/remote.rs#L53-L62

**Comment by jonhoo** [comment]
Ah, that's a good point! We really should move all of these tests to use local HTML files instead of relying on wikipedia. If you're up to the task, then please do go for it! Otherwise, I suppose the simpler way to go about it is to change the tests to use `en.wikipedia.org` directly.

**Comment by jonhoo** [comment]
I think this should now be fixed. And testing using local HTML files is tracked in https://github.com/jonhoo/fantoccini/issues/76
