### ISSUE TITLE
Update to tokio 1.0

### ISSUE THREAD

**Issue by MonsieurMan** [jonhoo/fantoccini#114]
Hi there !

I'll be using your library for a little raspberry project, checking tokyo I see there is a new version.

I'm in need of a little more training in Rust, would you be interested in me landing a PR for a migration to tokyo 0.3, or are there any current work on the matter ?

Thanks in advance,

**Comment by jonhoo** [comment]
Hi! Absolutely, I'd love one. I think we're probably going to be blocked on `hyper` not yet supporting `tokio 0.3`, but getting the ball rolling is a good idea :)

**Comment by MonsieurMan** [comment]
`hyper` author is going to wait a few weeks for `tokio 1.0` to ship, in order not to burden his users with potentially two breaking releases.

**Comment by jonhoo** [comment]
Now that `tokio 0.1` and `hyper 0.14` are out, I think we're only blocked on `hyper-tls` to get this out the door (https://github.com/hyperium/hyper-tls/issues/76)!

**Comment by jonhoo** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1684226

**Comment by bnoctis** [comment]
And [`tokio` 1.0 was released](https://tokio.rs/blog/2020-12-tokio-1-0). What a pace for them.

**Comment by peppizza** [comment]
hyper-tls v0.5 has been released with tokio 1.0, so if that was the last thing blocking then we should be free to update this lib

**Comment by jonhoo** [comment]
We unfortunately also currently have `warp` as a dev-dependency, which is still on `tokio 0.2` (issue here: https://github.com/seanmonstar/warp/issues/725). If someone wants to submit a PR that moves the tests to use `hyper` for the server instead (shouldn't be _too_ painful), then that would unblock the move!

**Comment by jonhoo** [comment]
https://github.com/jonhoo/fantoccini/pull/118
