### ISSUE TITLE
Please add a version note for tokio while using 0.2

### ISSUE THREAD

**Issue by bnoctis** [jonhoo/fantoccini#116]
I happened to run into this problem. `cargo run` said `#[tokio::main]` needs `tokio`, so I went to https://crates.io/crates/tokio to check it out. It said its version is 1.0.1. So I wrote my `Cargo.toml` `tokio = { version = '1.0.1', features = ['full'] }`. Then it went

> thread 'main' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler\` or `threaded_scheduler`', /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/spawn.rs:131:10

Not until I read `Cargo.toml` of `fantoccini` did I realize I should use the same version of tokio. Quite some confusion was it.

**Comment by jonhoo** [comment]
This should hopefully be fixed soon with https://github.com/jonhoo/fantoccini/issues/114 :)

**Comment by bnoctis** [comment]
Great! :smile:
