### ISSUE TITLE
Locator - tag name

### ISSUE THREAD

**Issue by leaty** [jonhoo/fantoccini#119]
I'm just wondering if this is in the plans, currently to get e.g. all "a" tags I need to use the full html source. Great job on the rest, works perfectly!

**Comment by jonhoo** [comment]
Glad to hear it! You should be able to do that with `Locator::Css("a")`, no?

**Comment by leaty** [comment]
Oh! So css isn't just stylesheet tags like classes, thank you so much! :+1:

**Comment by jonhoo** [comment]
Ah, sorry, yes, `Locator::Css` is _any CSS selector_. So you can do like `Css("section > header h1 a")` if you want.
