### ISSUE TITLE
Issue with 0.17.0 release

### ISSUE THREAD

**Issue by longfellowone** [jonhoo/fantoccini#124]
Receive the following error when running the example using 0.17.0 I receive no errors when using 0.16.0

Also the docs appear to be broken for this version as well

```
error[E0599]: no function or associated item named `new` found for struct `Client` in the current scope
 --> src\main.rs:6:25
  |
6 |     let mut c = Client::new("http://localhost:4444")
  |                         ^^^ function or associated item not found in `Client`

error: aborting due to previous error
```

**Comment by jonhoo** [comment]
Ooops, docs should be fixed with `0.17.1`!

`Client::new` was replaced by `ClientBuilder::native().build` in #115, but I've added a deprecated version of it back in `0.17.1` to help people upgrade :)
