### ISSUE TITLE
Warning in Sample app

### ISSUE THREAD

**Issue by sirxyzzy** [jonhoo/fantoccini#127]
The sample code gives warnings:

    warning: use of deprecated associated function `fantoccini::Client::new`: Prefer ClientBuilder::native

On this line in the Wikipeadia example:

        let mut c = Client::new("http://localhost:4444").await.expect("failed to connect to WebDriver");

**Comment by jonhoo** [comment]
Good catch — those examples were super old! I uploaded a new one to replace them :)
