### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by deven96** [jonhoo/fantoccini#128]
Tried running in a GCE instance and ran into the following error

```
  (unknown error: DevToolsActivePort file doesn't exist)
Mar 18 00:06:22 mythra-ce mythra[23385]:   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.
```

From what I've seen online, this is usually linked to starting chrome with one of the following args

```
--headless
--disable-shim
--remote-debugging-port=9222
```

Is there a way to do this from in a fantoccini client `Client::new()`

**Comment by deven96** [comment]
Nevermind... found the `goog:chromeOptions` capabilities

**Comment by deven96** [comment]
Perhaps I can adding the snippet about browser options from `test/common.rs` to the README would be very helpful

**Comment by jonhoo** [comment]
It is already documented under `ClientBuilder::capabilities`, but you're probably right that it could be surfaced better. If you find a good place in the docs to add a note, I'd be open to doing that!

**Comment by deven96** [comment]
Yeah perhaps a  short `ClientBuilder::capabilities` example showing `goog:chromeOptions` and `moz:firefoxOptions` can be displayed on the README?

**Comment by jonhoo** [comment]
That seems reasonable! I'd add it as an example in the documentation in `src/lib.rs`, and then it'll get surfaced in the `README` by running `cargo readme`.
