### ISSUE TITLE
[Question] Ignore TLS Errors

### ISSUE THREAD

**Issue by phunkpwnz** [jonhoo/fantoccini#131]
How would I configure the fantoccini Clientbuilder to ignore TLS Certificate errors like invalid hostname or certificate expiry. I currently get Hyper client errors when I come across those type of pages. 

Thanks in advance.

**Comment by jonhoo** [comment]
Hi! To do that you'd want to use `ClientBuilder::new` directly, which you can pass anything that implements [`hyper::Connect`](https://docs.rs/hyper/0.14//hyper/client/connect/trait.Connect.html). In your case, you can use something like [`hyper_tls::HttpsConnector::from`](https://docs.rs/hyper-tls/0.5.0/hyper_tls/struct.HttpsConnector.html) to construct one from a [`tokio_native_tls::TlsConnectorBuilder`](https://docs.rs/tokio-native-tls/0.3.0/tokio_native_tls/native_tls/struct.TlsConnectorBuilder.html), which lets you set things like how to handle certificates.

**Comment by phunkpwnz** [comment]
Awesome thanks! Closing my question.
