### ISSUE TITLE
Add support for setting cookies

### ISSUE THREAD

**Issue by LukeMathWalker** [jonhoo/fantoccini#140]
`fantoccini` exposes an API to delete/access existing cookies, but there is no way to set one.
I have seen the discussion in https://github.com/jonhoo/fantoccini/pull/130 - is `webdriver` still a blocker to implement this functionality? Is there a tracking issue I can follow there?

**Comment by jonhoo** [comment]
It's a bit of a mix. https://github.com/w3c/webdriver/issues/1238 definitely poses a challenge to providing a nice API for this. You can always set cookies through JavaScript, but then you can only set cookies for the _current_ domain (and not HttpOnly cookies).

**Comment by stevepryde** [comment]
Does `Client::add_cookie()` solve this one? There's a unit test for it also, which includes this:
```rust
    // Add a new cookie.
    use fantoccini::cookies::Cookie;
    let mut cookie = Cookie::new("cookietest", "fantoccini");
    cookie.set_domain(".wikipedia.org");
    cookie.set_path("/");
    cookie.set_same_site(Some(SameSite::Lax));
    c.add_cookie(cookie.clone()).await?;
```

**Comment by jonhoo** [comment]
Ah, so, unfortunately the WebDriver "AddCookie" API says:
> If [cookie name](https://www.w3.org/TR/webdriver1/#dfn-cookie-name) or [cookie value](https://www.w3.org/TR/webdriver1/#dfn-cookie-value) is [null](https://www.w3.org/TR/webdriver1/#dfn-null), **[cookie domain](https://www.w3.org/TR/webdriver1/#dfn-cookie-domain) is not equal to the [current browsing context](https://www.w3.org/TR/webdriver1/#dfn-current-browsing-context)’s [active document](https://www.w3.org/TR/webdriver1/#dfn-active-document)’s [domain](https://www.w3.org/TR/webdriver1/#dfn-domains)**, [cookie secure only](https://www.w3.org/TR/webdriver1/#dfn-cookie-secure-only) or [cookie HTTP only](https://www.w3.org/TR/webdriver1/#dfn-cookie-http-only) are not boolean types, or [cookie expiry time](https://www.w3.org/TR/webdriver1/#dfn-cookie-expiry-time) is not an integer type, or it less than 0 or greater than the [maximum safe integer](https://www.w3.org/TR/webdriver1/#dfn-maximum-safe-integer), return [error](https://www.w3.org/TR/webdriver1/#dfn-errors) with [error code](https://www.w3.org/TR/webdriver1/#dfn-error-code) [invalid argument](https://www.w3.org/TR/webdriver1/#dfn-invalid-argument).

Which means that API _only_ works for setting cookies for the current domain. I suppose we could close this since there is at least a way to set cookies _in general_, it just has this very onerous restriction.
