### ISSUE TITLE
Don't silently hit a URL for raw client cookie support

### ISSUE THREAD

**Issue by LegNeato** [jonhoo/fantoccini#148]
It is unexpected that using the raw client loads a completely different URL first to get cookies:

https://github.com/jonhoo/fantoccini/blob/6a7203e2307a397461ca633e0fd11719a88e339a/src/client.rs#L751

We should probably create typestates and specific functions to drive them and not do this automatically. Or perhaps let the URL be configured.

**Comment by jonhoo** [comment]
Yeah, it's really awkward, but as best as I can tell from the WebDriver standard, it's the only way to get cookies for a _given_ domain. This is tracked for the spec in https://github.com/w3c/webdriver/issues/1238.

**Comment by LegNeato** [comment]
My problem is the silent request is tripping bot detection, as this request + the "real" request happen too close together and the site sees me as a bot.

I'd like to at least be able to customize the url that is hit...would you take a PR to add that?

**Comment by jonhoo** [comment]
Yeah, a PR seems like a good idea!
