### ISSUE TITLE
Real-time discussion channel

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#17]
Having a channel (IRC, gitter, ...) to host real-time discussions could be advantageous to the project as developers could discuss features and implementations before work is started then reference conversations during code review, etc.

In my particular case I need to discuss some semantics with you (though I could create an issue for this, too) related to #6.

**Comment by jonhoo** [comment]
I made a Gitter room! I can't promise to be available there all the time, but it's at least a better medium for less formal and more detail-oriented discussions :)
