### ISSUE TITLE
Adding support for headless browser?

### ISSUE THREAD

**Issue by Atsukoro1** [jonhoo/fantoccini#176]
As described in [firefoxOptions](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions), the only way to run headless browser is by specifying **headless**. I have not found any way to pass arguments when creating the client with ClientBuilder.

I am currently creating client with Client builder like this ->
```rust
let cl: Client = ClientBuilder::native()
    .capabilities(
        HashMap::new()
            .insert(String::from("-headless"), String::from(""))  
            .into_iter()
            .collect::<Capabilities>()
    )
    .connect("http://127.0.0.1:4444")
    .await
    .expect(
        "Failed to connect to Webdriver, do you 
         have gecko driver and firefox binary installed?"
    );
```

**Comment by jonhoo** [comment]
As the Firefox docs you linked to mention, you need to pass in a capability named `moz:firefoxOptions` whose value should be something like:
```rust
serde_json::json!({ "args": ["--headless"] });
```

**Comment by zexa** [comment]
`serde_json::json` returns a `serde_json::Value` and it was unclear to me how to actually convert that into a `Capabilities`, so I ended up using `serde_json::from_str`:

```
    let client = ClientBuilder::native()
        .capabilities(serde_json::from_str(r#"{"moz:firefoxOptions": {"args": ["--headless"]}}"#)?)
        .connect("http://localhost:4444")
        .await?;
```

Does this look about right?

Also, we could probably use an example for this.

**Comment by jonhoo** [comment]
`Capabilities` is really just [a type alias for `serde_json::Map<String, serde_json::Value>`](https://docs.rs/fantoccini/latest/fantoccini/wd/type.Capabilities.html), so you can just use it directly :)
