### ISSUE TITLE
Cannot set `pageLoadOptions` in capabilities

### ISSUE THREAD

**Issue by aaronshim** [jonhoo/fantoccini#177]
No matter the value provided in `cap`, it gets overwritten here: https://github.com/jonhoo/fantoccini/blob/97b0d5fd94c9bda6ed5be4b298226b8c9d0de23b/src/session.rs#L627

Should it first check to see that it is not overwriting this value before resetting it? According to the [Selenium documentation](https://www.selenium.dev/documentation/webdriver/capabilities/shared/#pageloadstrategy), `normal`, `eager`, and `none` are all valid values.

**Comment by jonhoo** [comment]
Yep, good catch. Thanks for the PR!

**Comment by jonhoo** [comment]
Fixed now that https://github.com/jonhoo/fantoccini/pull/178 has been merged.
