### ISSUE TITLE
Allow lib users to pass capabilities to `Client::new`

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#18]
Capabilities allow, among other things, selecting which browser to use.

See [selenium/python/desired_capabilities](https://github.com/SeleniumHQ/selenium/blob/0aa2ab934ac245633c026a2bb39eb2d427fef20b/py/selenium/webdriver/common/desired_capabilities.py#L50-L128) for a list of pre-defined capabilities we could expose.

**Comment by kilork** [comment]
+1

Good to have possibility to start headless session, I think capabilities is a way to do this, right?

**Comment by jonhoo** [comment]
I'm actually not sure. In Firefox, I think the way to do this is by requesting an extra argument: https://developer.mozilla.org/en-US/Firefox/Headless_mode. But I'm not sure that counts as a capability...
