### ISSUE TITLE
BrowserStack requires `charset=utf-8` in `Content-Type` header on Selenium >= 4 

### ISSUE THREAD

**Issue by lamalex** [jonhoo/fantoccini#180]
Initiating a session on Selenium >= 4 requires the charset to be declared in the content type.
Although this feels like misuse on selenium's part, they seem to be dug in. See https://github.com/SeleniumHQ/selenium/issues/10913.

Setting `Content-Type: application/json; charset=utf-8` should not cause any breakage in existing implementations, but would expand compatibility.

**Comment by jonhoo** [comment]
Oh interesting! That should be a straightforward enough modification here:
https://github.com/jonhoo/fantoccini/blob/e015d3763e6d07accea2fac13d6b9140436d8f69/src/session.rs#L746

I'm super swamped for time at the moment, but happy to approve a PR!
