### ISSUE TITLE
Error when connecting to browserstack: Session not started or terminated

### ISSUE THREAD

**Issue by fiinnnn** [jonhoo/fantoccini#197]
Hi!

I'm trying to use `thirtyfour` to run tests on browserstack but whenever I try to connect it fails with: `NotW3C(Object {"message": String("Session not started or terminated")})`.

I contacted browserstack support and they said the following about the error message:
> The above error indicates that we received the command from your end after the session on BrowserStack stopped running.

It seems the error occurs immediately after the initial `NewSession` command.
I also tried connecting to a local selenium hub with fantoccini and connecting to browserstack using the python webdriver, both worked without any issues.

Do you have any idea what the issue could be?

Here's the code I used for testing:
```rust
let mut caps = DesiredCapabilities::chrome();

let bstack_options = json!({
    "os": "Windows",
    "osVersion": "11",
    "sessionName": name,
    "userName": "***",
    "accessKey": "***"
});

caps.add("bstack:options", bstack_options).unwrap();

let url = "https://hub.browserstack.com/wd/hub";

WebDriver::new(url, caps)
    .await
    .expect("failed to create driver")
```

**Comment by jonhoo** [comment]
That sounds like it might be a problem in your CI setup otherwise, or in thirtyfour somewhere. I'm afraid there's not much I can do to help here.
