### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by kokinarido** [jonhoo/fantoccini#2]
What should be running on the port 4444? chromedriver? Mine is running on 9515, but it's not available on localhost:9515

```
$ chromedriver 
Starting ChromeDriver 2.29 on port 9515
Only local connections are allowed.

```

And thus this:

` let mut c = Client::new("http://localhost:9515").unwrap();
` 
throws an exception:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed(Io(Error { repr: Os { code: 111, message: "Connection refused" } }))', src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

And I ran this:

```
$ geckodriver
1497632367412   geckodriver     INFO    Listening on 127.0.0.1:4444

```
and still got:

```
  let mut c = Client::new("127.0.0.1:4444").unwrap();
  
  ===>

  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed(Io(Error { repr: Os { code: 
  111, message: "Connection refused" } }))', src/libcore/result.rs:859
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by jonhoo** [comment]
The following works for me:
```console
$ chromedriver --port=4444
```
```rust
Client::new("http://localhost:4444");
```
So does just starting `geckodriver` and using the same Rust code to connect.
You're running these two commands on the same machine, right?

**Comment by kokinarido** [comment]
yes

**Comment by kokinarido** [comment]
now it sees the chrome driver. but

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotW3C(Object({"message": String("session not created exception: Missing or invalid capabilities\n  (Driver info: chromedriver=2.29,platform=Linux 4.11.5-1-ARCH x86_64)")}))', src/libcore/result.rs:859`

**Comment by jonhoo** [comment]
Are you using the latest commit on `master`? And a recent version of Chrome + chromedriver?

**Comment by kokinarido** [comment]
yes

**Comment by jonhoo** [comment]
Seems this is happening on the latest version of Chrome for me too -- not clear why. I suspect Chrome's WebDriver implementation is deviating from the W3C spec again, so you should stick with `geckodriver` for now (since it's a conforming solution).

**Comment by kokinarido** [comment]
the latest version of geckodriver

```
thread 'main' panicked at 'unexpected webdriver error; webdriver returned error: connection refused', /home/user123/.cargo/registry/src/github.com-1ecc6299db9ec823/fantoccini-0.6.4/src/lib.rs:173
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jonhoo** [comment]
`geckodriver` takes a little while to start up -- make sure you wait for the server to be ready before trying to launch the Rust program. Beyond that, I don't know what to tell you. It works on my machine with geckodriver :/

**Comment by jonhoo** [comment]
Apparently the `chromedriver` issue is [known](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1796&can=1&q=capabilities&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary), and has been fixed with `chromedriver 2.30`.

**Comment by jonhoo** [comment]
@kokinarido one workaround that might work for you for `chromedriver` is to replace
```rust
.map(|s| s.contains("cannot find dict 'desiredCapabilities'"))
```
with
```rust
.map(|s| s.contains("Missing or invalid capabilities"))
```
in the code. There should only be one place that it appears.

**Comment by Phrohdoh** [comment]
I noticed that in the geckodriver snippet a protocol was not given.

I could be wrong but I *believe* the `http` protocol is necessary.
