### ISSUE TITLE
Migrate from rustc-serialize to serde

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#20]
The serde family of crates has been the de-facto solution for de/serialization for some time now.

**Comment by Phrohdoh** [comment]
Ref the webdriver/geckodriver work on this: https://bugzilla.mozilla.org/show_bug.cgi?id=1396821

**Comment by phungleson** [comment]
Hey guys, interested to pick this up, is this the matter of migrating `rustc_serialize` to using this https://github.com/serde-rs/serde?

**Comment by Phrohdoh** [comment]
Migrating the usage of `rustc_serialize` in this crate to `serde` (and `serde_json`).

We may have to do some ugly work (converting between `serde` and `rustc_serialize` types) to communicate with our dependency `webdriver`.

**Comment by jonhoo** [comment]
I'd prefer to wait for webdriver to move before we do, otherwise we'll do a bunch of conversion work that we'll later have to undo. I don't think this is really causing us any issues at the moment that'd make this a high priority?

**Comment by Phrohdoh** [comment]
It appears that the transition from `rustc_serialize` to `serde` is complete in `webdriver`.

https://hg.mozilla.org/mozilla-central/rev/7f2c542df6fd

Unfortunately, according to crates.io, the published crate has not been updated in 3 months (so this change is likely not in there yet).

https://crates.io/crates/webdriver

**Comment by jonhoo** [comment]
I wonder how we ping them about that now...

**Comment by Phrohdoh** [comment]
> The mailing list for webdriver discussion is tools-marionette@lists.mozilla.org (subscribe, archive).
>
> There is also an IRC channel to talk about using and developing webdriver in #ateam on irc.mozilla.org.

The IRC channel is probably a good place to start.

**Comment by jonhoo** [comment]
I have most of the implementation of this now done, but can't build locally due to a too-new openssl version :( Sadly, this can't be fixed without https://github.com/jonhoo/fantoccini/pull/34. I'll ping @tcr over there.
