### ISSUE TITLE
How to specify options for webdriver?

### ISSUE THREAD

**Issue by ksubox** [jonhoo/fantoccini#213]
Hello,
I need to connect to existing instance of Chrome over Chromedriver.
So I need to specify debuggerAddress = "127.0.0.1:xxxx".
Could you tell me how to do this?

Actually I need something like that in Java:
```
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption(“debuggerAddress”,”localhost:9595“);
ChromeDriver driver = new ChromeDriver(options);
```

**Comment by jonhoo** [comment]
You should be able to include those via `capabilities` is my guess, which you can set using [`ClientBuilder::capabilities`](https://docs.rs/fantoccini/0.20.0-rc.4/fantoccini/struct.ClientBuilder.html#method.capabilities).
