### ISSUE TITLE
Can you automate the geckodriver session initialization?

### ISSUE THREAD

**Issue by SRK7Kyros** [jonhoo/fantoccini#220]
I was working on my personal project, which requires webscraping so I looked into this library.
The problem that came to my mind is that you need to have something-geckodriver already running, which i dont really know how to start programmatically...
Can somebody explain it to me?

**Comment by mdrokz** [comment]
> I was working on my personal project, which requires webscraping so I looked into this library. The problem that came to my mind is that you need to have something-geckodriver already running, which i dont really know how to start programmatically... Can somebody explain it to me?

Hey i use a macro like this 

```rs
macro_rules! spawn {

    ($f: expr) => {
        std::thread::spawn(move || {
            Command::new($f).output().expect("failed to spawn");
        });
    };

    ($f: expr, $($x: expr),*) => {
        std::thread::spawn(move || {
            Command::new($f)
            $(.arg($x))*.output().expect("failed to spawn");
        });
    };
}

macro_rules! exec {
    ($f: expr) => {
        match Command::new($f).output() {
         Ok(x) => println!("{}", str::from_utf8(&x.stdout).expect("failed to parse")),
         Err(e) => panic!(e.raw_os_error()),
        }
    };

    ($f: expr, $($x: expr),*) => {
        match Command::new($f)
            $(.arg($x))*.output() {
                Ok(x) => println!("{}", str::from_utf8(&x.stdout).expect("failed to parse")),
                Err(e) => panic!(e.raw_os_error()),
            }
    };
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    spawn!("geckodriver");
}
```

**Comment by jonhoo** [comment]
As @mdrokz says, it _should_ just be a matter of running the `geckodriver` command. Beyond that, running the WebDriver host is sort of outside the scope of this project :)
