### ISSUE TITLE
Get console log messages

### ISSUE THREAD

**Issue by AustinHellerRepo** [jonhoo/fantoccini#224]
There doesn't seem to be a way to register for the `entryAdded` event as defined by the DevTools Protocol (https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json). This would be fine if I could instead call something like `get_logs` on the `Client`, but that doesn't seem to exist either.
I'd be happy to contribute to this project in order to create this functionality if someone could point me in the correct direction.

**Comment by jonhoo** [comment]
Hi! This library (currently) only implements the WebDriver spec, and not the Chrome DevTools protocol. For that, I think you need to use @stevepryde's `thirtyfour` crate which has some support for it :) I'd like to keep this library focused on just one protocol, and then have DevTools be in a different crate that can be tested and such on its own, and then have some higher layer crate (like thirtyfour) do the combining.
