### ISSUE TITLE
WheelActions needed

### ISSUE THREAD

**Issue by KirDontsov** [jonhoo/fantoccini#235]
Hi, thx for a grate solution for chromdriver!

But can you provide a solution for scroll a div container to the bottom, via mouse wheel actions, and a small example how to use it?

**Comment by jonhoo** [comment]
Ah, wheel actions already exist in 0.20, the final stable version of that just hasn't been released yet! Give `0.20.0-rc.7` a try and generate an [`ActionSequence`](https://docs.rs/fantoccini/0.20.0-rc.7/fantoccini/actions/struct.ActionSequence.html) that includes a [`WheelAction::Scroll`](https://docs.rs/fantoccini/0.20.0-rc.7/fantoccini/actions/enum.WheelAction.html#variant.Scroll).

This functionality landed in #216, so maybe @jaboatman can give you a good usage example?

**Comment by jonhoo** [comment]
Going to close this one since the functionality exists. Always happy to take PRs to improve the docs though!
