### ISSUE TITLE
chrome fails to change browser name

### ISSUE THREAD

**Issue by meeeerkat** [jonhoo/fantoccini#264]
The browser name is set to "chrome" but after creation (in headless mode) it is "chrome-headless-shell".
It seems some websites do not accept this browser name and return a blank page (or is it something else?).

```rust
use fantoccini::{ClientBuilder};
use tokio;
use serde_json;

#[tokio::main]
async fn main() -> Result<(), fantoccini::error::CmdError> {
    let caps = serde_json::from_str(
        r#"{"browserName":"chrome","goog:chromeOptions":{"args":["--headless"]}}"#,
    ).unwrap();

    let c = ClientBuilder::native()
        .capabilities(caps)
        .connect("http://127.0.0.1:4444")
        .await
        .expect("failed to connect to WebDriver");

    dbg!(c.capabilities());

    Ok(())
}
```

**Comment by jonhoo** [comment]
`fantoccini` passes the WebDriver capabilities directly to the hosting server (well, the hosting driver), so if this doesn't get picked up by Chrome then that's a problem either with `chromedriver` or Chrome itself :)
