### ISSUE TITLE
Improve wait_* style methods

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/fantoccini#27]
Currently, `wait_for_find` [just spins](https://github.com/jonhoo/fantoccini/blob/ee0c585f6fb97c1718bd684055172a3ae067d02b/src/lib.rs#L1260) trying to look for the element in question. A much better strategy would be to use [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) (specifically [`observe`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe) on the document root) to wait for new elements to be added to the page, and only re-execute the webdriver `find` when something new has appeared.

**Comment by zhiburt** [comment]
Hey @jonhoo, what do you think about adding wrappers for `wait_*` functions with timeout parameter?
They possible can be done like this

```rust
    pub async fn wait_for_find_with_timeout(&mut self, search: Locator<'_>, timeout: Duration) -> Result<Element, error::CmdError> {
        tokio::time::timeout(timeout, self.wait_for_find(search))
    }
```

 As you've pointed out users can do it on there own but it might be helpful to have out of the box.

PS: Thanks for such a good crate

**Comment by jonhoo** [comment]
So, I think wrappers like that actually add relatively little sadly. For that, the user can already just do the `tokio::time::timeout` call themselves. What I think I'd like to see is something a little more nuanced where, if the request times out, the WebDriver requests is cancelled. I don't know how feasible that is though? My concern is that the user issues a request with a timeout, it times out, then they issue another request, and that request fails or hangs for a long time because the browser already has a pending request...

**Comment by zhiburt** [comment]
Could I be enlighten here since I am not proficient in webdriver architecture?:)

Do you tend to say that canceling requests by `tokio::time::timeout` might cause issues in the browser because it handles requests one by one or as if the browser handles it in a way that each request is handled in some `thread/goorutine/ etc.` the fast canceling of requests may cause slowing browser hugely since it will handle a ton of dead `thread/goorutine/ etc.`. That's your concern about such a way of timeout handling right?

**Comment by jonhoo** [comment]
Yes, essentially. Although not necessarily that there are lots of dead requests, but rather that we only run one WebDriver request at the time currently. Imagine that you run a request that invokes an infinite loop in JavaScript. You time out the future that waits for that request, but the connection to the WebDriver instance is still held up by that (infinite) request. If you issue another fantoccini request, that request will forever be queued behind the still ongoing one.
