### ISSUE TITLE
Errors related to the request to open cookies

### ISSUE THREAD

**Issue by ChengCY-2254** [jonhoo/fantoccini#270]
I don't speak English, so this issus is a machine translation, which may be a little wrong. Please forgive me.
---
I am trying to encode and decode cookies, but the relevant [API](https://docs.rs/cookie/0.18.1/cookie/struct.Cookie.html#method.parse) will return cookie::ParseError, which makes it impossible to accurately define it in my custom error. I don't want to add a duplicate crate for an Error, so I request an alias or something to open up the cookie::ParseError error.

**Comment by jonhoo** [comment]
You should generally be defining your own error type, not trying to re-use fantoccini's error type for your own errors :)
