### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by hhamud** [jonhoo/fantoccini#279]
found this mentioned somewhere in issues thinking that it was a fantoccini problem but turns out it was a geckodriver issue.

> Client::new should not fail just because another session is already open. I believe this is only the case for geckodriver, and I believe it should be considered a bug there. Works fine with chromedriver for example (this is why the firefox tests in fantoccini all have #[serial]).

If you could add this caveat in clientbuilder connect it would be very helpful. 

Willing to do this myself if you are willing to accept the PR.

**Comment by jonhoo** [comment]
I'd love a PR please!
