### ISSUE TITLE
Set value of input without name attribute

### ISSUE THREAD

**Issue by kraai** [jonhoo/fantoccini#31]
Please add a method for setting the value of an `input` element that doesn't have a `name` attribute.

I'm trying to set the value of the `input` element whose `id` is `autocomplete2` on https://www.reservecalifornia.com/CaliforniaWebHome/Facilities/AdvanceSearch.aspx.  The element doesn't have a `name` attribute, so `Form::set_by_name` doesn't seem to work.  `Client::find` can find the element, but `Element` doesn't appear to have a method for setting its value.

**Comment by jonhoo** [comment]
Ah, yes you're right. There should probably be a `set` method that takes a `Locator`. Adding this should probably be pretty straightforward. You should be able to copy/paste `set_by_name`, and make it take a `Locator` instead (the first two lines would then go away). You could then change `set_by_name` to call `set`. Think you could submit a PR?
