### ISSUE TITLE
Futures 0.3

### ISSUE THREAD

**Issue by tiberiusferreira** [jonhoo/fantoccini#46]
Since futures will be stable in 1.36, and the latest futures crate version has already ```Updated to stabilized futures_api``` as per https://github.com/rust-lang-nursery/futures-rs/releases  I think it would be a big ergonomic upgrade for the users if Fantoccini updated to futures 0.3. 

This would allow us to use the nightly async await feature without having to convert between 0.1 and 0.3 before every await call. 

This would alleviate issues such as https://github.com/jonhoo/fantoccini/issues/43 

Is this change something Fantoccini would be willing to embrace?

**Comment by jonhoo** [comment]
Absolutely! I think the tricky thing is going to tie this into [`tokio-futures`](https://github.com/tokio-rs/tokio/tree/master/tokio-futures).

**Comment by jonhoo** [comment]
Go take a look at https://github.com/jonhoo/fantoccini/pull/51 :tada:
