### ISSUE TITLE
Add to rust bus

### ISSUE THREAD

**Issue by pickfire** [jonhoo/fantoccini#49]
https://users.rust-lang.org/t/bus-factor-1-for-crates/17046

**Comment by jonhoo** [comment]
I'm a little worried about that approach, like others in that thread, without further protocol for exactly how the "bus" will work. A clear policy for how the bus operates, along with some measure of accountability would be welcome. In the meantime, I'd be very happy to add someone as a maintainer to this crate if such a person steps up!

**Comment by pickfire** [comment]
Okay, that seems fair enough, hope this project can get a maintainer soon. Currently I don't have the time to maintain another project, sometimes only just contributing small parts here and there.

Maybe you could have post it to the rust-lang forum like https://users.rust-lang.org/t/winit-0-20-the-state-of-windowing-in-rust-and-a-request-for-help/29485.
