### ISSUE TITLE
Add a way to reconnect to an existing session

### ISSUE THREAD

**Issue by Follpvosten** [jonhoo/fantoccini#57]
I don't think this is implemented yet, and I also don't really need it yet, but it would be nice to have; in my project, I may want to re-use the same session if the long-running process controlling it is restarted at some point.

At the moment, if I persist a session with `Client::persist` and then try to reconnect to the session (using `Client::with_capabilities` or `Client::new`), I get a `SessionNotCreated(WebDriverError { error: SessionNotCreated, message: "Session is already started", stack: "", delete_session: false })`.

I suppose the way to handle this would be adding a method like `Client::with_existing_session(webdriver: &str, session_id: &str)` and a corresponding `Session::from_id(webdriver: &str, id: &str)` or similar, which tries to connect to the given session using its ID (no idea how that's gonna work internally right now, but that would likely be the API). Then we can store the session ID and reconnect later.

I'll look into implementing this when I can find the time :)

**Comment by jonhoo** [comment]
Awesome -- that sounds like a cool feature!

**Comment by travisbrown** [comment]
@Follpvosten Have you looked into this? I implemented a very basic version today since I needed it myself, but it only does exactly what I need.

**Comment by travisbrown** [comment]
@jonhoo Mind if I open a WIP PR with a simple version of this for the sake of discussion?

**Comment by jonhoo** [comment]
Not at all, please do!
