### ISSUE TITLE
The basic example might be broken?

### ISSUE THREAD

**Issue by jethrosun** [jonhoo/fantoccini#58]
I have the geckodriver running on port 4444 but  `cargo run` in the `example/basic_setup` gives the following errors:

```sh
~/tmp/fan/exa/basic_setup:master> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/basic_setup`
thread 'thread 'tokio-runtime-worker-2tokio-runtime-worker-0' panicked at '' panicked at 'not yet implemented: failed to connect to WebDriver: SessionNotCreated(WebDriverError { error: SessionNotCreated, message: "Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line", stack: "", delete_session: false })called `Option::unwrap()` on a `None` value', ', src/main.rssrc/libcore/option.rs::16378::2621
```

I have tried it on macOS and linux and I got the same error. Any idea what is wrong here? Thx

```sh
nightly-x86_64-apple-darwin (default)
rustc 1.39.0-nightly (f0b58fcf0 2019-09-11)
```

**Comment by jonhoo** [comment]
Ah, yes, `geckodriver` is pretty finicky if you aren't using a "standard" Firefox install. I need to run `geckodriver` with:
```console
$ geckodriver -b /usr/bin/firefox-developer-edition
```
So that it explicitly knows which binary to launch. You can sort of see this from the panic message you get if you read far enough along:
> error: SessionNotCreated, message: "Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line"

I'd be happy to accept a PR that makes this error easier to discover.
