### ISSUE TITLE
Request: Add an API for interacting w/ Cookies

### ISSUE THREAD

**Issue by dljsjr** [jonhoo/fantoccini#59]
_Full disclaimer: I'm not a web expert and I'm new to using WebDriver so this might be possible using functionality that lives outside of Fantoccini, so feel free to close if that's the case_

Currently, the Client does not support an easy way to interact with the current Session's cookie store unless you make a raw request and interact with the request builder/response which will only give you the cookies for that particular domain.

It would be nice to be able to interact with a Session's cookie store from the high level API to enable things like serializing/deserializing persistent cookies in applications where you may want to remember things like user log-in state. Examples of where this could be useful might include improving CI/CD test times by not requiring repeated log-ins. It could also be useful in scraper-backed user-facing applications that use technologies like OAuth instead of Basic Auth, so that the user doesn't have to repeatedly authorize the login every time they launch the application (even if it's automated).

**Comment by jonhoo** [comment]
Yup, I agree, that would be really handy! But unfortunately all WebDriver [supports](https://www.w3.org/TR/webdriver2/#get-all-cookies) is to fetch all the cookies of the _current document_. Maybe that would still be useful to expose though? There are also commands for adding a cookie, and for deleting one. Together, those three may at least get you close to what you want? It should be pretty easy to add support for those to fantoccini if you want to open a PR for me to look at!

**Comment by dljsjr** [comment]
I might play around with it this weekend! Thanks for pointing me to that WebDriver documentation.

**Comment by Boscop** [comment]
Yes, please support adding cookies :)

**Comment by dljsjr** [comment]
@jonhoo sorry I never started looking at this! The site I was scraping doubled down on their bot detection and so I pivoted the project 🤷‍♂️ I might still take a stab at it some time.

**Comment by aksiksi** [comment]
@jonhoo I'm working on a PR to add the 5 cookie-related functions as defined in [16 Cookies](https://www.w3.org/TR/webdriver1/#cookies).

One challenge with defining APIs is in how to pass in/return a cookie.  The two options I'm considering are:

### 1. Accept/return cookies as `serde_json::Value`s

Straightforward implementation, just pass everything along to the `webdriver` crate and you're done.  Users will need to make sure the parameters are of the correct types by checking the spec.

### 2. Accept/return cookies as a [`cookie::Cookie`](https://docs.rs/cookie/0.15.0/cookie/struct.Cookie.html)

This requires a bit more code within `fantoccini` to convert to/from JSON cookies for WebDriver. In particular, WebDriver encodes the `Max-Age` of a cookie as a u64 Unix timestamp, whereas `cookie::Cookie` requires a `Duration`.  We'll probably need to pull in a datetime crate like `chrono` to be able to resolve this difference.

The two advantages of this approach are that users will be able to:

1. More easily inspect cookies returned by WebDriver (e.g., `client.get_name_cookie(&name).await?.value()`
2. Construct cookies dynamically via [`cookie::CookieBuilder`](https://docs.rs/cookie/0.15.0/cookie/struct.CookieBuilder.html).

Thoughts?

**Comment by aksiksi** [comment]
Actually, I hit a bit of a snag while implementing the `add_cookie` operation... `webdriver::command::AddCookieParameters` does not implement `Serialize`, which means that `fantoccini` can't serialize the struct to JSON for the POST request :(

I don't actually need `add_cookie`, but I'm not sure if it would make sense to add all but one of the supported cookie operations.

**Comment by jonhoo** [comment]
Sorry it took me a while to get back to this! I think `cookie::Cookie` is indeed the way to go :+1: 

That's awkward about `Serialize`. I've found the maintainers of `webdriver` pretty receptive to suggestions, so if you suggest it there, it'll probably be implemented pretty quickly! In the meantime though, I think it's okay to add all but one :)
