### ISSUE TITLE
Request: Implement `select_by_value` for `select` elements

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#6]
I am attempting to do this locally but am tripping over Rc.

Current code is in ~[a gist](https://gist.github.com/Phrohdoh/34715986f26d93ce2bcbde94ef795071) (which is likely to become a 404 link once I fix this issue).~ in the following comment.

Any help / input much appreciated!

**Comment by Phrohdoh** [comment]
Status update:

I have resolved the Rc issue (I do not know if my approach is correct though):

```rust
pub struct Select<'c> {
    c: &'c Client,
    e: Element,
}

impl<'c> Select<'c> {
    /// TODO: docs
    pub fn from(c: &'c Client, e: Element) -> Self {
        Self { c, e }
    }

    /// TODO: docs
    pub fn select_by_value(self, value: &'c str) -> impl Future<Item = Client, Error = error::CmdError> + 'c {
        let locator = format!("option[value=\"{}\"]", value); // TODO: Escape `value`
        let locator = webdriver::command::LocatorParameters {
            using: webdriver::common::LocatorStrategy::CSSSelector,
            value: locator,
        };

        // TODO: Use FindELementElements
        let cmd = WebDriverCommand::FindElementElement(self.e.e, locator);
        self.c.dup().issue_wd_cmd(cmd).and_then(move |(c, r)| {
            // NOTE: I am working on this part now. Need to convert `r` to an element, I believe.
            Ok(c)
        })
    }
}
```

**Comment by jonhoo** [comment]
I'm not entirely sure why the `is_selected` branch is necessary? Couldn't you always just click the option? I also wonder if we should just fetch all the options under the `select` and do the checking for value in code. It'll save us the escaping of the value in the CSS selector, at the cost fo fetching more options (which probably doesn't matter all that much). Thoughts?

**Comment by Phrohdoh** [comment]
If you always click an option you may be deselecting an already clicked option in a multi-select dropdown.

I do like the sound of fetching all options up front and doing comparisons in our code. Performance evaluations needed of course but the idea doesn't hurt.

**Comment by jonhoo** [comment]
Yeah, I think I'd accept something like this. I'm a little tight for time in the coming weeks, but would be happy to take a look at and mentor a PR!

**Comment by Phrohdoh** [comment]
Unfortunately I have run out of time for this and have been moved onto other projects that currently do not require this functionality meaning this issue is up-for-grabs for someone else to take a stab at.

**Comment by Phrohdoh** [comment]
I found myself revisiting this mentally and think I just now understood a point you made @jonhoo.

I was previously under the assumption that `click` would deselect currently-selected options (which may be the case, I have not verified this one way or another) but if that *is not* the case then just a single `click` will work which means that the `is_selected` branch is indeed unnecessary.

If a `click` does deselect then perhaps setting the `selected` attr explicitly will be "good enough."

**Comment by jonhoo** [comment]
Those are all good questions, and I don't really have an answer. I suspect the best way to deal with this is similar to how we distinguish between `Element::click` and `Element::follow`. One emulates a real user click, while the other deals directly with attributes. The various `Form::submit_*` methods are the same. Having two different accessors that implement the two behaviors you outline seems like a decent solution :)

FWIW: I'm *fairly* sure that clicking an already selected option will not unselect it (unlike, e.g., `<input type="checkbox">`).

**Comment by Phrohdoh** [comment]
I didn't articulate that well but what I meant was in a dropdown with multiple options if you have A selected then click B that A will be unselected (unless it is a multi-select and the user initiates a multi-select action [shift+click]).
