### ISSUE TITLE
BadURL(RelativeUrlWithoutBase) when using `safaridriver` w/ Safari 13/macOS Mojave on fantoccini stable (0.11.9)

### ISSUE THREAD

**Issue by dljsjr** [jonhoo/fantoccini#60]
I'm working on a scraper for a site that doesn't have a proper OAuth API and I'd like to be able to support multiple browsers. I've been prototyping w/ `geckodriver` without issue but today I tried to use `safaridriver` and I'm not even able to issue a simple `client.goto()` or run the basic example as I immediately error out with the error in the issue title. Apple *claims* that `safaridriver` on Safari 12 and later supports the W3C API and not the Selenium API (https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_12_and_later) but given their track record with docs in the last few years I wouldn't be totally shocked if this is a half-truth.

It's not immediately obvious to me that there's a way to extract the offending URL from the CmdError or ParseError to provide more information. I'd love to help debug if you don't have easy access to macOS, maybe you could point me to a place in the internals that I should start digging/instrumenting?

**Comment by dljsjr** [comment]
Don't know if this helps but here's a diagnostic log from `safaridriver`:

```text
2019/10/29 14:57:22:707  HTTPServer: POST http://localhost:4444/session
2019/10/29 14:57:22:707  HTTPServer: {"capabilities": {"alwaysMatch":{"browserName":"safari","goog:chromeOptions":{"w3c":true},"pageLoadStrategy":"normal","safari:diagnose":"true"},"firstMatch":[{}]}}
2019/10/29 14:57:22:709  AutomationProtocol: SEND {"method":"Automation.createBrowsingContext","params":{"presentationHint":"Window"},"id":1}
2019/10/29 14:57:22:831  AutomationProtocol: RECV {"result":{"handle":"page-9F92E572-C2D1-4090-BE16-10D89DC82332","presentation":"Window"},"id":1}
2019/10/29 14:57:22:832  AutomationProtocol: SEND {"method":"Automation.switchToBrowsingContext","params":{"browsingContextHandle":"page-9F92E572-C2D1-4090-BE16-10D89DC82332","frameHandle":""},"id":2}
2019/10/29 14:57:22:949  AutomationProtocol: RECV {"result":{},"id":2}
2019/10/29 14:57:22:949  HTTPServer: --> HTTP 200
2019/10/29 14:57:22:949  HTTPServer: --> {"value":{"sessionId":"7B1E0F67-EF6E-4DFD-AE5F-3D5E35B5B2EB","capabilities":{"safari:platformVersion":"10.14.6","safari:automaticInspection":false,"webkit:WebRTC":{"DisableICECandidateFiltering":false,"DisableInsecureMediaCapture":false},"goog:chromeOptions":{"w3c":true},"browserVersion":"13.0.2","strictFileInteractability":false,"safari:useSimulator":false,"browserName":"Safari","safari:platformBuildVersion":"18G103","setWindowRect":true,"acceptInsecureCerts":false,"safari:automaticProfiling":false,"pageLoadStrategy":"normal","safari:diagnose":true,"platformName":"macOS"}}}
2019/10/29 14:57:22:954  HTTPServer: GET http://localhost:4444/session/7B1E0F67-EF6E-4DFD-AE5F-3D5E35B5B2EB/url
2019/10/29 14:57:22:954  AutomationProtocol: SEND {"method":"Automation.isShowingJavaScriptDialog","params":{"browsingContextHandle":"page-9F92E572-C2D1-4090-BE16-10D89DC82332"},"id":3}
2019/10/29 14:57:23:037  AutomationProtocol: RECV {"result":{"result":false},"id":3}
2019/10/29 14:57:23:037  AutomationProtocol: SEND {"method":"Automation.getBrowsingContext","params":{"handle":"page-9F92E572-C2D1-4090-BE16-10D89DC82332"},"id":4}
2019/10/29 14:57:23:047  AutomationProtocol: RECV {"result":{"context":{"handle":"page-9F92E572-C2D1-4090-BE16-10D89DC82332","active":false,"url":"","windowOrigin":{"x":0,"y":600},"windowSize":{"width":800,"height":600}}},"id":4}
2019/10/29 14:57:23:047  HTTPServer: --> HTTP 200
2019/10/29 14:57:23:047  HTTPServer: --> {"value":""}
2019/10/29 14:57:23:049  HTTPServer: DELETE http://localhost:4444/session/7B1E0F67-EF6E-4DFD-AE5F-3D5E35B5B2EB

**Comment by jonhoo** [comment]
Hmm, that's interesting. That sounds like an error coming from the URL-handling library fantoccini uses. What is the backtrace when your program crashes? That should help in narrowing things down.

**Comment by dljsjr** [comment]
@jonhoo What's the commit hash for 0.11.9? I'm trying to avoid using Nightly for the project I'm working on and I can't see any tags or anything for releases. I see the release date on Crates.io is July 18th but the commits around that time are for 0.11.8 and 0.12 based on the Cargo.toml

**Comment by dljsjr** [comment]
PR for this is open, not sure if the fix itself is the "right" thing to do but it works. I'll open a separate issue for the other bug I'm seeing.
