### ISSUE TITLE
Request: A way to connect to an already created session by passing through a session ID

### ISSUE THREAD

**Issue by Grav3y** [jonhoo/fantoccini#65]
Hi all, I am currently trying to do automation with chromeDriver and I am having a tough time with passing through args for my sessions. A way around this I thought would be to initialize the session through curl then connect to it and control it with Fantoccini. I may just be missing the point here but I have been struggling with this for a while and I thought this would be a potential fix. Feel free to leave comments/suggestions :)

**Comment by jonhoo** [comment]
Out of curiosity, why did you close this? Did you find a solution?

**Comment by Grav3y** [comment]
> Out of curiosity, why did you close this? Did you find a solution?

There was already an issue open asking for the same thing. I didn’t want to be repetitive :)
