### ISSUE TITLE
Request: Add functionality to run a script every time you navigate before the page loads

### ISSUE THREAD

**Issue by GRVYDEV** [jonhoo/fantoccini#66]
Hi all, I need to run a script every time i load a page that occurs before the page actually loads. I am currently looking into a solution for this but if anyone knows how its done I would love to know how. I have currently tried running client.execute() before client.goto() but that doesn't seem to do the trick (which makes sense). Will continue searching for a way to do this and will update here if I find one.

**Comment by jonhoo** [comment]
Hmm, I'm not sure the WebDriver API even really lets you do that sadly. Please do post if you find a way to do it though!

**Comment by Grav3y** [comment]
This is possible in puppeteer so there has to be some way. I need to further my understanding a bit and then revisit it :)
