### ISSUE TITLE
Multi-threaded pooling of clients results in BrokenPipe

### ISSUE THREAD

**Issue by bitemyapp** [jonhoo/fantoccini#68]
I've got code that looks like this:

```
    tokio::spawn(async move {
        scrape_worker(scraping.clone()).await;
    }
    );
```

if I change it to await the `scrape_worker` without spawning a task it works fine. The error message I get right now is:

```

[2020-01-16T20:49:06Z DEBUG scraping_rs] Starting scrape of url: "https://phantomjs.org/"
thread 'tokio-runtime-worker' panicked at 'gai background task failed: JoinError::Cancelled', /home/callen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/connect/dns.rs:144:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2020-01-16T20:49:06Z ERROR scraping_rs] Error instantiating client error was: Lost(Custom { kind: BrokenPipe, error: "WebDriver session was closed while waiting" })
thread 'tokio-runtime-worker' panicked at 'Failed to pull a client from the pool: Backend(NotJson("Couldn\'t instantiate client"))', src/libcore/result.rs:1165:5
```

With the relevant error being: `Lost(Custom { kind: BrokenPipe, error: "WebDriver session was closed while waiting" })`.

It reproduces with Chromedriver 79.0.3945.36 and geckodriver 0.26.

Based on https://github.com/jonhoo/fantoccini/blob/master/tests/common.rs I feel like multi-threaded operation was intended here but I'm not sure what I'm doing wrong. I'm using [deadpool](https://github.com/bikeshedder/deadpool) to pool the clients:

```rust
#[async_trait]
impl deadpool::Manager<Client, Error> for Manager {
    async fn create(&self) -> Result<Client, Error> {
        let mut client = Client::new("http://localhost:9515").await.map_err(|err| {
            error!("Error instantiating client error was: {:?}", err);
            fantoccini::error::CmdError::NotJson("Couldn't instantiate client".to_string())
        })?;
        client.persist().await?;
        Ok(client)
    }
    async fn recycle(&self, conn: &mut Client) -> deadpool::RecycleResult<Error> {
        Ok(())
    }
}
```

It dies on the very first URL, never spawns a browser window.

**Comment by jonhoo** [comment]
Hmm, it looks to me as though it fails to connect in the first place due to `hyper`. That first panic looks suspicious. If you could find a way to reproduce this without `deadpool`, that'd be helpful!

**Comment by bitemyapp** [comment]
@jonhoo I was able to make it work by switching to deadpool's support for unmanaged pooling in `master`, however I'm running into it not seeming very performant and like Tokio is doing the work in a single-threaded way. cc @bikeshedder any idea why the managed pooling would break something like this?

The unmanaged instantiation looks like:

```rust
    let pool = Pool::from(vec![
        create_client().await?,
        create_client().await?,
        create_client().await?,
        create_client().await?,
        // create_client()?,
    ]);
```

Then my spawns and awaits look like:

```rust
    let handle1 = tokio::spawn(async move {
        scrape_worker(scraping1).await;
    });
    let handle2 = tokio::spawn(async move {
        scrape_worker(scraping2).await;
    });
    let handle3 = tokio::spawn(async move {
        scrape_worker(scraping3).await;
    });
    let handle4 = tokio::spawn(async move {
        scrape_worker(scraping4).await;
    });

    handle1.await;
    handle2.await;
    handle3.await;
    handle4.await;
```

I'm probably still doing something wrong though.

**Comment by bikeshedder** [comment]
This is rather strange behaviour indeed and doesn't seam to be caused by deadpool at first glance. Could you please try a single threaded executor and see if that changes anything:

```rust
#[tokio::main(core_threads = 1, max_threads = 1)]
```

Actually the `unmanaged` pool should even be slightly faster as it does not care about creating and recycling clients on demand and has even less overhead. btw. you can now use `deadpool = "0.5.0"` which got released on `crates.io` today which includes the `unmanaged` pool implementation.

**Comment by bitemyapp** [comment]
@bikeshedder Backtracking to repro the problem has cleared it up I think. I wasn't binding the JoinHandle and await'ing the spawned task from tokio.

Doing this repro's the error:

```rust
    tokio::spawn(async move {
        scrape_worker(scraping).await;
    });
```

Doing this does not:

```rust
    let handle1 = tokio::spawn(async move {
        scrape_worker(scraping1).await;
    });
    handle1.await;
```

I don't think this is relevant to either fantoccini or deadpool any longer, but would either of you have any idea why the program might seem concurrent but _not_ parallel even with multiple threads? I'll close the issue meanwhile.

**Comment by bitemyapp** [comment]
My issue might be https://old.reddit.com/r/rust/comments/dt6u0s/joined_futures_will_run_concurrently_not_in/

Investigating.
