### ISSUE TITLE
Does not seem to work with multiple redirects

### ISSUE THREAD

**Issue by maximih** [jonhoo/fantoccini#7]
I am trying to use `fantoccini` to automate the login and fecthing of some data from an energi provider website.

The [main landing page](https://www.goteborgenergi.se/Mina_sidor) is redirecting to an [external page](https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw) for authentication but it does that by going through an intermediary page.

This intermediary page is not even visible in the browser when doing the whole thing manually but`fantoccini`always reports this intermediary page as `current_url()` even if on the screen I can see that it reached the authentication page.

So, it looks like `fantoccini` gets locked on the first redirect url. Is there a way to make it advance to the current page that it's displayed on the screen?

I did several tries with `wait_for_navigation()` and `wait_for_find()` but I always end up in a deadlock.

If needed, I can add some of the code I've tried.

Looking forward for your feedback.

Thanks

**Comment by jonhoo** [comment]
Hmm, that's strange. It seems to work fine for me?
```rust
extern crate fantoccini;
extern crate futures;
extern crate tokio_core;

use fantoccini::Client;

fn main() {
    let mut core = tokio_core::reactor::Core::new().unwrap();
    let c = Client::new("http://127.0.0.1:4444", &core.handle());
    let c = core.run(c).unwrap();

    core.run(c.goto("https://www.goteborgenergi.se/Mina_sidor"))
        .unwrap();
    for _ in 0..20 {
        println!("{:?}", core.run(c.current_url()));
        ::std::thread::sleep(::std::time::Duration::from_millis(100));
    }
    core.run(c.close()).unwrap();
}
```
```console
$ cargo +nightly r
   Compiling y v0.1.0 (file:///home/jon/tmp/y)
    Finished dev [unoptimized + debuginfo] target(s) in 4.9 secs
     Running `target/debug/y`
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://www.goteborgenergi.se/my.policy")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
Ok("https://idpaut.service.tieto.com/idp/gbgenergi/authenticate/authGbgF51UnPw")
```
Or am I missing something?

**Comment by maximih** [comment]
It seems I did not wait long enough. I was calling `current_url()` 2-3 times immediately after `goto()`and then it was always returning the intermediary url. 

I will try adding a loop and check the `current_url()` until it gets to the authentication page.

Thanks a lot for your help.

**Comment by jonhoo** [comment]
Sure thing! For what it's worth, it looks like `chromedriver` gets to the final page a great deal faster than `geckodriver` does. Don't know if it matters to you though :)

**Comment by jonhoo** [comment]
You could also stick a call to `wait_for_navigation` inside that loop. That should help.
