### ISSUE TITLE
Request: Add ability to switch frames

### ISSUE THREAD

**Issue by hgzimmerman** [jonhoo/fantoccini#70]
I'm trying to test a webpage that makes use of an iframe using this library.
Unfortunately, in order to interact with elements inside of iframes, the Client needs to switch into the iframe.
There exists command enums in the webdriver crate for performing the necessary actions, so this should be possible:
* `WebDriverCommand::SwitchToFrame`
* `WebDriverCommand::SwitchToParentFrame`

I have tried to do this myself in my fork, but I could not get my changes to work, with errors I don't quite recall being returned. 
The PR with the relevant changes is available here: https://github.com/hgzimmerman/fantoccini/pull/1/files#diff-b4aea3e418ccdb71239b96952d9cddb6R765 (due to vendoring and rust version lock at work, I am basing this off of the v0.11.9 release, but the changes shouldn't be materially different against master).

This very well may be a bug in the webdriver crate, but since they lack a github page for the library, I'm filing the issue here with the hope that someone more familiar with that library may be able to assist.

firefox version: Mozilla Firefox 72.0.1
geckodriver version: geckodriver 0.26.0
OS version: Ubuntu 18.04.3 LTS
library version: v0.11.9 (fork)

EDIT:
This is the error following calling any of my `frame` functions:
```
WebDriverErr(Lost(Custom { kind: BrokenPipe, error: "WebDriver session was closed while waiting"}))
```

**Comment by jonhoo** [comment]
Hmm, that looks an awful lot like the webdriver _server_ crashed. Could you try running `geckodriver` with debug output and see if it prints anything helpful?

**Comment by hgzimmerman** [comment]
Given the following output, it doesn't look like it crashes:

```
...
1580416571084	Marionette	DEBUG	0 -> [0,10,"WebDriver:ElementClick",{"id":"02744e0f-9292-440f-a8cc-c3bdf9e9d6eb"}]
1580416571096	Marionette	TRACE	[15] Received DOM event beforeunload for http://localhost:9001/login
1580416571103	Marionette	TRACE	[15] Received DOM event pagehide for http://localhost:9001/login
1580416571104	Marionette	TRACE	[15] Received DOM event unload for http://localhost:9001/login
1580416571133	Marionette	TRACE	[15] Received DOM event DOMContentLoaded for http://localhost:9001/login_mfa
1580416571173	Marionette	TRACE	[15] Received DOM event pageshow for http://localhost:9001/login_mfa
1580416571174	Marionette	DEBUG	0 <- [1,10,null,{"value":null}]
1580416571179	webdriver::server	DEBUG	<- 200 OK {"value":null}
1580416571180	webdriver::server	DEBUG	-> POST /session/eabb10ca-f06c-4be6-b292-578f09ce3e83/element {"using":"xpath","value":"//*[@id=\"mfa_iframe\"]"}
1580416571200	Marionette	DEBUG	0 -> [0,11,"WebDriver:FindElement",{"using":"xpath","value":"//*[@id=\"mfa_iframe\"]"}]
1580416571202	Marionette	DEBUG	0 <- [1,11,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"f0420685-5391-48b8-9297-a053423b4f50"}}]
1580416571202	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"f0420685-5391-48b8-9297-a053423b4f50"}}
```

**Comment by jonhoo** [comment]
Hmm, but I also don't see any calls there that try to switch frames?

**Comment by hgzimmerman** [comment]
That's fair. I'd assume that it crashes before its able to emit logs regarding the switch frames request.

I'll see if I can come up with a minimal reproduction example and PR adding the frame functions sometime in the near future.
