### ISSUE TITLE
How to get page source after page load?

### ISSUE THREAD

**Issue by Boscop** [jonhoo/fantoccini#78]
Is it the case that I only have to `await` `Client::goto`?
And is it also the case that `Client::source` always returns the current source (modified by any js code that ran before)?

**Comment by jonhoo** [comment]
Waiting for navigation with `await goto` followed by `await source` should give you what you want. At least if I'm reading the [WebDrive specification](https://www.w3.org/TR/webdriver1/#dfn-get-page-source) right. Ultimately, fantoccini just "does what the browser does", so that's the best answer I can give :)

**Comment by Boscop** [comment]
I'm asking because people are suggesting workarounds for determining when the page has finished loading:

E.g. checking for DOM changes by comparing it repeatedly:
https://stackoverflow.com/questions/10720325/selenium-webdriver-wait-for-complex-page-with-javascript-to-load/43794026#43794026

Or checking if references to elements on the current page have gone stale:
https://rollout.io/blog/get-selenium-to-wait-for-page-load/

**Comment by jonhoo** [comment]
The answer to that is complicated, but essentially "fantoccini does what WebDriver does". Now, "what WebDriver does" varies by browser, so it's not always obvious what you'll get, but the requirements from the spec are outlined in "[Waiting for navigation to complete](https://www.w3.org/TR/webdriver1/#dfn-waiting-for-the-navigation-to-complete)", which is executed whenever you [change the URL](https://www.w3.org/TR/webdriver1/#dfn-navigate-to). Ultimately, it essentially boils down to waiting for the browser to deem the document's [readiness](https://html.spec.whatwg.org/#current-document-readiness) as "complete". What _that_ means is dictated by [this procedure](https://html.spec.whatwg.org/#the-end), which is more or less "load the page and run all the initial JavaScript".

The workarounds you mention are mostly related to people who want to wait _longer_ than that. They want to wait for some async stuff that _also_ has to load for the page to be ready to interact with. The browser doesn't know about anything like that, so it just makes its best guess (per the procedures above) as to when navigation has "completed". And that's what fantoccini inherits :)
