### ISSUE TITLE
the trait bound `std::option::Option<impl futures::Future>: futures::Future` is not satisfied

### ISSUE THREAD

**Issue by januslinhc** [jonhoo/fantoccini#8]
Hi Jonhoo,

I have followed your first code example of "clicking around on Wikipedia". However, I got the following issue: 

```
error[E0277]: the trait bound `std::option::Option<impl futures::Future>: futures::Future` is not satisfied
  --> src/main.rs:46:10
   |
46 |     core.run(fin).unwrap();
   |          ^^^ the trait `futures::Future` is not implemented for `std::option::Option<impl futures::Future>`

error: aborting due to previous error
```

**Comment by jonhoo** [comment]
Hmm, that's quite weird. There is an `impl Future for Option<F> where F: Future` in [`futures`](https://docs.rs/futures/0.1/futures/future/trait.Future.html#impl-Future), so this should work just fine. What versions of `futures` and `tokio`/`tokio-core` are you using? What version of the compiler?

**Comment by januslinhc** [comment]
```
[dependencies]
tokio-core = "0.1.16"
futures = "0.1.19"
fantoccini = "0.8.1"
```

```
rustc 1.26.0-nightly (f5631d9ac 2018-03-24)
```

**Comment by jonhoo** [comment]
Oh, interesting! It seems like they removed this `impl` in `futures 0.1.19`: https://github.com/rust-lang-nursery/futures-rs/pull/729. I'll try to come up with a fix that works in both.

**Comment by januslinhc** [comment]
@jonhoo Thank you so much!!

**Comment by jonhoo** [comment]
It looks like there isn't really a nice way to get this to work on both versions :/ I'll change the code to use
```rust
if let Some(fin) = c.close() {
    core.run(fin).unwrap();
}
```
which should work in both despite being pretty ugly..

**Comment by jonhoo** [comment]
FWIW, this was caused by an upstream bug that has now been fixed. I'll keep the explicit `if let Some(..)` in the for future compatibility with futures `0.2` though.
