### ISSUE TITLE
`Form::set_by_name` doesn't match textarea elements

### ISSUE THREAD

**Issue by Vypo** [jonhoo/fantoccini#80]
The [selector][0] should probably be changed from `input[name='{}']` to something like `*[name='{}']"`?

[0]: https://github.com/jonhoo/fantoccini/blob/8623807a9444d6dafe5676297a5832af91b27e5c/src/lib.rs#L1174

**Comment by jonhoo** [comment]
Ah, that's an interesting point. I think you're right. Though I think we don't even need the `*`, as it is implied. Would you mind filing a PR?
