### ISSUE TITLE
More ergonomic API for writing tests that always terminate

### ISSUE THREAD

**Issue by Vypo** [jonhoo/fantoccini#81]
The `wait_for_*` family of functions as they exist now are super useful, but if the element never appears, my automated tests spin forever.

Would it be possible to have an API that looks something like:

```rust
let client = fantoccini::Client::new("http://127.0.0.1/").await?;

// Tries once and fails
client.find(Locator::Css("#foo")).await?;

// Retries forever
client.find(Locator::Css("#foo")).retry_forever().await?;

// Retries for a certain amount of time
client.find(Locator::Css("#foo")).retry_for(Duration::from_secs(1)).await?;

// Retries until a deadline
let start = Instant::now();
let timeout = Duration::from_secs(10);
client.find(Locator::Css("#foo")).retry_until(timeout + start).await?;
```

**Comment by jonhoo** [comment]
This should already be doable by using [`tokio::time::timeout`](https://docs.rs/tokio/0.2/tokio/time/fn.timeout.html). Would that work for you?

**Comment by ctron** [comment]
I am not sure what the outcome of this issue is. I would also be interested in a timeout.

If it already exists, maybe updating the example would be an idea.

**Comment by jonhoo** [comment]
The example _should_ be a fairly straightforward use of [`tokio::time::timeout`](https://docs.rs/tokio/1/tokio/time/fn.timeout.html). Something along the lines of
```rust
tokio::time::timeout(
    std::time::Duration::from_secs(1),
    async {
        loop {
            match client.find(Locator::Css("#foo")) {
                Ok(e) => break Ok(e),
                Err(CmdError::NoSuchElement(_)) => {},
                Err(e) => break Err(e),
            }
        }
    }
);
```
I think we could probably implement a simple wrapper around this if someone's willing to do the work to write up a PR :)
