### ISSUE TITLE
Element does not implement ToJson as advertized

### ISSUE THREAD

**Issue by ipkiss42** [jonhoo/fantoccini#84]
The `Element::execute()` doc states:

```
args is available to the script inside the arguments array. Since Element implements ToJson,
you can also provide serialized Elements as arguments, and they will correctly serialize to DOM
elements on the other side.
```

However, `Element` doesn't seem to implement `ToJson`. See [this](https://github.com/jonhoo/fantoccini/search?q=ToJson&unscoped_q=ToJson) for example.

**Comment by jonhoo** [comment]
Ah, yes, that's a good point! I wonder when that went away accidentally. Probably quite a while ago to be honest. The fix here is to derive `Serialize` on `Element`, and then mark `client` as [skipped](https://serde.rs/attr-skip-serializing.html) and [flatten](https://serde.rs/attr-flatten.html) the contained `webdriver::WebElement`. I _think_ that should do it, though you'd want to test it as well.

**Comment by ipkiss42** [comment]
Just to be clear: are you planning to do it or are you suggesting this as a pull request?

I don't mind to give it a try if it helps, but I don't want to duplicate the effort.

**Comment by jonhoo** [comment]
If you could submit a PR, that'd be great!
