### ISSUE TITLE
Fantoccini panics when there is a "stale element reference" error

### ISSUE THREAD

**Issue by ipkiss42** [jonhoo/fantoccini#88]
A [stale element reference](https://www.w3.org/TR/webdriver/#dfn-stale-element-reference) is possible, e.g. when a reference is kept for too long and reused. Unfortunately, this causes a panic due to this:

https://github.com/jonhoo/fantoccini/blob/93e849a8ca1b1eb1cb36b398eb425f2a23efb43c/src/session.rs#L785-L788

I created #87 to address this issue.

**Comment by lucaswxp** [comment]
This should be closed as of https://github.com/jonhoo/fantoccini/pull/87
