### ISSUE TITLE
Add API support for selecting between tabs / windows

### ISSUE THREAD

**Issue by tcr** [jonhoo/fantoccini#9]
I believe this is part of WebDriver, and I would use this in my project were it available, but for now I just wanted to log the feature request.

If it becomes more urgent I'll try to take a crack at implementing this.

(Thanks for the great work on fantoccini!)

**Comment by jonhoo** [comment]
I'm a bit strapped for time at the moment, but I think adding support for this should be pretty straightforward. Happy to look at a PR! :D

**Comment by jonhoo** [comment]
This was closed by #75 :tada:
