### ISSUE TITLE
Network Requests Intercepting

### ISSUE THREAD

**Issue by whizsid** [jonhoo/fantoccini#91]
This is a very helpfull crate. But I want to intercept all network requests that sending from the browser. And want to redirect all requests for a specific URL after adding some additional HTTP headers.

Expected:-
```rust

browser.set_interception(|data|{
       let response = make_request(data);
       InterceptDecision::Response(response);
})

```

This feature is already implemented in [rust-headless-chrome](https://github.com/atroche/rust-headless-chrome/blob/1f63d697d8491fc222eb118a25684e380e00ecbb/src/browser/tab/mod.rs#L39).

**Comment by jonhoo** [comment]
Unfortunately I don't think this is something you can do through the cross-browser [WebDriver API](https://www.w3.org/TR/webdriver1/#list-of-endpoints), it's only something you can do when interacting directly with the Chrome DevTools protocol (which this crate does not implement).

**Comment by whizsid** [comment]
Thank you @jonhoo . I will try it in another way.

**Comment by edsky** [comment]
How did you do it.I need to judge whether the network request is over.

**Comment by whizsid** [comment]
@edsky I created a browser extension and installed it using #92 .  Used the browser extensions API to intercept all HTTP requests. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests . This is the only W3C way to do this. And it will work only with geckodriver. Because other drivers does not support to install a browser extension.

**Alternative Method**
You can make a custom proxy server.
