### ISSUE TITLE
question: does it support selection of options?

### ISSUE THREAD

**Issue by zhiburt** [jonhoo/fantoccini#93]
I've run into an issue that `select_by_value` waits forever and not select an item.

I did check that [element](https://github.com/jonhoo/fantoccini/blob/a7fb72c6171e2e4e14acbd533b162f7dba80518d/src/lib.rs#L1116-L1119) is found for my case and I can obtain `text` value for example but when it tries to click on it it waits forever.

Does `select_by_value` method supports selection of options?
In other words is it possible to select an item in `<select>` block?

**Comment by jonhoo** [comment]
Huh, that's weird... The only thing `click` does is issue an `ElementClick` command to the browser:
https://github.com/jonhoo/fantoccini/blob/a7fb72c6171e2e4e14acbd533b162f7dba80518d/src/lib.rs#L1039-L1040

Could you try running the browser driver with `--verbose` to see that it indeed receives that command, and any errors it might give? Perhaps the item isn't visible?

**Comment by zhiburt** [comment]
Fairly it was at night so I didn't notice it was not 'editable'. It was on the page but in not clickable state :(.
Sorry for bothering.

By the way is there any way to check if element is editable(There is a way to interact with it)?
I've seen in C# webdriver something like `enabled` https://stackoverflow.com/a/17077786.
If it's not implemented it could be done in similar way as `wait_for_find`. Not sure if it actually cover edition of `<input>` elements.
 
```rust
        let element = self.wait_for_find(search).await?;
        loop {
            match element.clone().click().await {
                Ok(..) => break Ok(element),
                Err(error::CmdError::Standard(e))
                    if e.error == webdriver::error::ErrorStatus::ElementClickIntercepted => {}
                Err(e) => break Err(e),
            }
        }
```

**Comment by jonhoo** [comment]
I think the trick would be to use [`Element::attr`](https://docs.rs/fantoccini/0.13.1/fantoccini/struct.Element.html#method.attr) to get that attribute of the given element. I don't think I want `select_by_value` to incorporate waiting, since it is not itself a `wait` method.

**Comment by zhiburt** [comment]
It was actually a snippet of `wait_for_find_editable` :)
